export const USER_SIGNIN_API  = 'USER_SIGNIN_API'
export const NAVIGATE = 'NAVIGATE';



export const GET_DATA_PROJECT_CATEGORY ='GET_DATA_PROJECT_CATEGORY'
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA'

export const CREAT_PROJECT_SAGA = 'CREAT_PROJECT_SAGA'


export const GET_PROJECT_LIST ='GET_PROJECT_LIST'